### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by gulsunde** [mattjj/pyhsmm-slds#15] opened 2017-05-24 20:05 UTC
from pyslds.models import DefaultSLDS

I get an error in the first step

**Comment by mattjj** [comment] 2017-05-25 01:41
You'll have to be more specific if you want help. The best thing to do would be to include a script or command that reproduces the error, along with the traceback you saw, info about how you installed this code, what version of Python and any relevant libraries you're using, and what platform you're on.

I think there's a good chance this is related to [recent pylds installation problems](https://github.com/mattjj/pylds/issues/15) that we're cleaning up.

**Comment by gulsunde** [comment] 2017-05-25 02:05
Hi,
I really wanted to be specific but I got the error just in the stage of pip
install myslds...

**Comment by mattjj** [comment] 2017-05-25 02:23
So that's already one piece of useful information to include. You can also include a traceback from the pip install, especially if you run it with the verbose flag.

**Comment by gulsunde** [comment] 2017-05-25 02:25
It says the second line of the code gives an error. (The first piece of
code given in the Background)

I am done with the installation part now sry it was the previous problem...

**Comment by gulsunde** [comment] 2017-05-25 17:54
eph@eph-XPS-8900:~/Documents/5000$ python slds_test1.py
Traceback (most recent call last):
  File "slds_test1.py", line 24, in <module>
    from pyslds.models import DefaultSLDS, DefaultWeakLimitStickyHDPSLDS
  File "/usr/local/lib/python2.7/dist-packages/pyslds/models.py", line 13,
in <module>
    from pyslds.states import HMMSLDSStatesPython, HMMSLDSStatesEigen,
HSMMSLDSStatesPython, \
  File "/usr/local/lib/python2.7/dist-packages/pyslds/states.py", line 11,
in <module>
    from pylds.states import LDSStates
  File "/usr/local/lib/python2.7/dist-packages/pylds/states.py", line 8, in
<module>
    from pylds.lds_messages_interface import info_E_step, info_sample,
kalman_info_filter, kalman_filter, E_step
  File
"/usr/local/lib/python2.7/dist-packages/pylds/lds_messages_interface.py",
line 10, in <module>
    from pylds.lds_messages import \
ImportError: No module named lds_messages
eph@eph-XPS-8900:~/Documents/5000$


This is the error I got for the code you added as:

PyLDS exposes a variety of classes and functions for working with linear
dynamical systems. For example, the following snippet will generate
synthetic data from a random model:

import numpy.random as nprfrom pylds.models import DefaultLDS

D_obs = 1       # Observed data dimension
D_latent = 2	# Latent state dimension
D_input = 0	    # Exogenous input dimension
T = 2000  	    # Number of time steps to simulate

true_model = DefaultLDS(D_obs, D_latent, D_input)
inputs = npr.randn(T, D_input)
data, stateseq = true_model.generate(T, inputs=inputs)
# Compute the log likelihood of the data with the true params
true_ll = true_model.log_likelihood()

The DefaultLDS constructor initializes an LDS with a random rotational
dynamics matrix. The outputs are data, a T x D_obs matrix of observations,
and stateseq, a T x D_latent matrix of latent states.

Now create another LDS and try to infer the latent states and learn the
parameters given the observed data.

# Create a separate model and add the observed data
test_model = DefaultLDS(D_obs, D_latent, D_input)
test_model.add_data(data)
# Run the Gibbs sampler
N_samples = 100def update(model):
    model.resample_model()
    return model.log_likelihood()

lls = [update(test_model) for _ in range(N_samples)]

We can plot the log likelihood over iterations to assess the convergence of
the sampling algorithm:

# Plot the log likelihoods
plt.figure()
plt.plot([0, N_samples], true_ll * np.ones(2), '--k', label="true")
plt.plot(np.arange(N_samples), lls, color=colors[0], label="test")
plt.xlabel("iteration")
plt.ylabel("training likelihood")
plt.legend(loc="lower right")

**Comment by slinderman** [comment] 2017-07-25 14:21
I'm closing this issue as we haven't seen any update on it in the past few months.  It looks like it likely arose from an improper installation of `pylds`, which in turn failed to build the `lds_messages` code. 

@gulsunde please reopen and provide an update if this is still affecting you.

**Closed as completed by slinderman** 2017-07-25 14:21 UTC
