### ISSUE TITLE
installation problem?

### ISSUE THREAD

**Issue by eliotmoss** [mattjj/pyhsmm-slds#12] opened 2017-05-10 14:53 UTC
With considerable gnashing of teeth, I seem finally to have installed all the dependencies and pyslds itself.  When I try "from pyslds import models" I was getting failures in pybasicbayes under python3 (I filed an issue there).  Under python2 I get a problem in pylds: "No module names lds_messages".  What can I do to advance my efforts in trying out pyslds?

**Comment by slinderman** [comment] 2017-05-10 15:01
Hi Eliot,
A few quick questions:
1. What platform are you on? All of our testing is done on Mac.
2. Are you installing the dependencies from pypi (e.g. with `pip install
pybasicbayes`) or from github source (e.g. `git clone
git@github.com:mattjj/pybasicbayes.git`
followed by `pip install -e .` from the pybasicbayes directory?)  I would
suggest the latter since the github source will be most up to date, and
much of this code is under active development.

The specific issue of `No module named lds_messages` suggests that the
cython files were not actually compiled.

Thanks,
Scott

**Comment by eliotmoss** [comment] 2017-05-10 15:37
Thank you, Scott.

I had been trying python2.7 and pythong3.6m under cygwin (on Windows 10).

So I switched to a linux server that has 2.7.5 and 3.4.3.  I have now
installed pybasicbayes, pyhsmm, pylds, and pyslds all from a .zip file
from the github site.  Under python 3 I still get the inability to find
DiagonalRegression and under python 2 I get the inability to find
lds_messages.

Are there other files for which I should use your versions?  Should
I upgrade the server to 3.6 and try again?

Regards - Eliot

**Comment by eliotmoss** [comment] 2017-05-10 15:38
I will also try git clone and installing from that.

Maybe the .zip files are the same older versions ...

Regards - EM

**Comment by slinderman** [comment] 2017-05-10 15:51
Python 2.7 and Python 3 should all be supported.

Let's get to the bottom of the DiagonalRegression issue first.
DiagonalRegression is defined in pybasicbayes/distributions/regression.py;
can you make sure you see it in that file?  If it's present and `from
pybasicbayes.distributions import DiagonalRegression` still fails, double
check that `pybasicbayes.__file__` points to the expected path.

**Comment by mattjj** [comment] 2017-05-10 17:11
Thanks for your interest!

I agree you want to get to the bottom of the DiagonalRegression issue first, since that code should be easy to find and it might just be a path issue.

To say a bit more about the other, compilation-related issue, the lds_messages module is an extension module generated by cython and ultimately by your C/C++ compiler. That is, the file that needs to be loaded by Python is named lds_messages.so (on POSIX systems). That compilation process is performed by setup.py in the standard way, which can be invoked by running `pip install -e .` from the git root directory for each repository (though setup.py can also be run more directly in the usual ways). If you try to import any extension modules without running the standard Python setup process, it's expected to get 'no module named' errors.

(Side note: it's not accurate that all our testing is on macOS; I run this code on Arch and Ubuntu GNU/Linux distributions more often than on macOS. However, I only run things with Python 2.7.)

**Comment by eliotmoss** [comment] 2017-05-10 18:28
On 5/10/2017 1:11 PM, Matthew Johnson wrote:
> Thanks for your interest!
>
> I agree you want to get to the bottom of the DiagonalRegression issue first, since that code should
> be easy to find and it might just be a path issue.
>
> To say a bit more about the other, compilation-related issue, the lds_messages module is an
> extension module generated by cython and ultimately by your C/C++ compiler. That is, the file that
> needs to be loaded by Python is named lds_messages.so (on POSIX systems). That compilation process
> is performed by setup.py in the standard way, which can be invoked by running |pip install -e .|
> from the git root directory for each repository (though setup.py can also be run more directly in
> the usual ways). If you try to import any extension modules without running the standard Python
> setup process, it's expected to get 'no module named' errors.
>
> (Side note: it's not accurate that all our testing is on macOS; I run this code on Arch and Ubuntu
> GNU/Linux distributions more often than on macOS. However, I only run things with Python 2.7.)

Ok -- having used git clone (instead of requesting zip files) and reinstalled all four packages
(pybasicbayes, pyhsmm, pylds, and pyslds), the failure to find DiagonalRegression has gone away.
Good progress!

What still happens, under both python 2 and 3, is "No module named lds_messages".  I searched
under pylds and /usr/lib/python... and found no .so file for lds_messages.  So it seems clear
it is not getting built.  What do we do to build it?

Regards - Eliot

**Comment by eliotmoss** [comment] 2017-05-10 18:30
I discover that there are no .c or .cpp files under pylds ... EM

**Comment by eliotmoss** [comment] 2017-05-10 20:57
Ok, I've solved the lds_models issue.  pylds has an unstated
dependence on Cython.  I was not previously aware of the chain
.pyx -> .c -> .so and the use of cython to process .pyx files.
Maybe it would be reasonable to add that package dependency?

So now I can build and import pyslds.  Woo hoo!  I'll try
to run examples and such and let you know if everything
seems ok.

Regards - Eliot

**Comment by slinderman** [comment] 2017-05-10 22:08
Glad you got to the bottom of it Eliot. Sorry that dependency was not more
explicit.  As I look back on the code, I see that we have logic in there to
warn if Cython is not present, but the installation won't fail outright.

@mattjj If I recall correctly, we did this so that folks who pip install
won't need cython, but in order for that to work I think we need to add
`recursive-include pylds *.c` to the manifest.  I'm looking at my local
cythonized copy and lds_messages.pyx gets compiled to C, not C++.  I went
ahead and made that change here
https://github.com/mattjj/pylds/commit/ea283e7bef154f341e28ad2859670bfdf0e1d551


Can you give it a test run and push to pypi if it works?

**Comment by mattjj** [comment] 2017-05-11 02:35
Wow, nice sleuthing! Glad you got it to work.

I forgot about that detail: to repeat what @slidnerman said, you need cython to build the GitHub version of the code (for several of these repositories), since we don't check in the cython-generated .c files. However, when we upload the package to pypi, we do intend to include the generated .c files (via MANIFEST.in), so that users installing from pypi don't need cython. I wonder if there's a way to include cython as a dependence if installing from the git repo, but not include it as a dependence for pypi.

@slinderman, I think your diagnosis of the pypi problem is right: we missed `recursive-include pylds *.c`! I'll upload that now.

I'm going to close this issue, but please reopen if it's not resolved.

**Closed as completed by mattjj** 2017-05-11 02:35 UTC

**Comment by eliotmoss** [comment] 2017-05-11 02:47
On 5/10/2017 10:35 PM, Matthew Johnson wrote:
> Wow, nice sleuthing! Glad you got it to work.
>
> I forgot about that detail: to repeat what @slidnerman said, you need cython to build the GitHub
> version of the code (for several of these repositories), since we don't check in the
> cython-generated .c files. However, when we upload the package to pypi, we do intend to include the
> generated .c files (via MANIFEST.in), so that users installing from pypi don't need cython. I wonder
> if there's a way to include cython as a dependence if installing from the git repo, but not include
> it as a dependence for pypi.
>
> @slinderman <https://github.com/slinderman>, I think your diagnosis of the pypi problem is right: we
> missed |recursive-include pylds *.c|! I'll upload that now.
>
> I'm going to close this issue, but please reopen if it's not resolved.

Thank you both for the responsive assistance!

I have gotten the demos to run under python2 and pop up png files across a network connection.
For python3 that isn't working - it complains about not finding tkinter (weird since that's
built in to python AFAIK).  Seems to be something about the matplotlib install, but I am not
sure what to do about it.

Regards - Eliot
